const allMovies = [
{ id: 1, title: "Avengers: Endgame", image: "image/endgame.png", rating: 4.5, year: 2023, duration: "2j 15m", category: "action", href: "film1.html" },
{ id: 2, title: "Parasite", image: "image/OIP (1).png", rating: 4.5, year: 2023, duration: "2j 15m", category: "action", href: "film2.html" },
{ id: 3, title: "Inception", image: "image/memek.png", rating: 4.5, year: 2023, duration: "2j 15m", category: "action", href: "film3.html" },
{ id: 4, title: "The Shawshank Redemption1", image: "image/kontol.jpg", rating: 4.5, year: 2023, duration: "2j 15m", category: "action", href: "film4.html" },
{ id: 5, title: "The Shawshank Redemption2", image: "image/kontol.jpg", rating: 4.5, year: 2023, duration: "2j 15m", category: "action", href: "film5.html" },
{ id: 6, title: "The Shawshank Redemption3", image: "image/kontol.jpg", rating: 4.5, year: 2023, duration: "2j 15m", category: "action", href: "film6.html" },
{ id: 7, title: "Joker", image: "image/joker.png", rating: 4.5, year: 2023, duration: "2j 15m", category: "action", href: "film7.html" },
{ id: 8, title: "Pulp Fiction", image: "image/pulp.jpg", rating: 4.5, year: 2023, duration: "2j 15m", category: "action", href: "film8.html" },
{ id: 9, title: "The Dark Knight", image: "image/knight.jpg", rating: 4.5, year: 2023, duration: "2j 15m", category: "action", href: "film9.html" },
{ id: 10, title: "Forrest Gump1", image: "image/OIP.jpg", rating: 4.5, year: 2023, duration: "2j 15m", category: "action", href: "film10.html" },
{ id: 11, title: "Forrest Gump2", image: "image/OIP.jpg", rating: 4.5, year: 2023, duration: "2j 15m", category: "action", href: "film11.html" },
{ id: 12, title: "Forrest Gump3", image: "image/OIP.jpg", rating: 4.5, year: 2023, duration: "2j 15m", category: "action", href: "film12.html" },
{ id: 13, title: "Vidio Jomok Bintang", image: "images/film1.jpg", rating: 4.5, year: 2023, duration: "2j 15m", category: "action", href: "filmaksi1.html" },
{ id: 14, title: "Jomok 2", image: "images/film2.jpg", rating: 4.5, year: 2023, duration: "2j 15m", category: "action", href: "watch.html?movie=jomok-2" },
{ id: 15, title: "Jomok 3", image: "images/film3.jpg", rating: 4.5, year: 2023, duration: "2j 15m", category: "action", href: "watch.html?movie=jomok-3" },
{ id: 16, title: "Judul Film 4", image: "images/film4.jpg", rating: 4.5, year: 2023, duration: "2j 15m", category: "action", href: "watch.html?movie=judul-film-4" },
{ id: 17, title: "Judul Film 5", image: "images/film5.jpg", rating: 4.5, year: 2023, duration: "2j 15m", category: "action", href: "watch.html?movie=judul-film-5" },
];
